service: c5-wutyee-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  firstfunction:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /hnin
          method: get
      
  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /wutyee
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - WutyeeQueue
              - Arn


resources:
  Resources:
    WutyeeQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "wutyee-queue"


plugins:
  - serverless-offline